# Generated by Django 3.0.3 on 2020-06-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='producttxn', to='inventory.Product'),
        ),
    ]
