# Generated by Django 3.0.3 on 2020-05-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
